<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Home extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Barang_model');
        $this->load->model('Customer_model');
        $this->load->model('Cs_model');

    }

    public function index()
    {
		//if(!$this->session->userdata('logined') || $this->session->userdata('logined') != true)
		//{
			//redirect('/');
		//}

		//$this->load->view('home');
        //$this->load->view('HomeLogin');
        $this->load->view('Home');
        
    }

    public function login(){
        $this->load->view('Login2');
    }

    public function homeLoginAdm(){
        $this->load->view('HomeLoginAdm');
    }

    public function homeLoginCust(){
        $this->load->view('HomeLoginCust');
    }

    public function setting()
    {
        $this->load->view('Setting');
    } 

    public function shop(){
        $data['barang'] = $this->Barang_model->ambil_data();
        $this->load->view('Shop/Shop', $data);
    }

    public function shopAdm(){
        $this->load->view('Shop/ShopAdm');
    }

    public function shopCust(){

        $data['barang'] = $this->Barang_model->ambil_data();
        $this->load->view('Shop/ShopCust', $data);
    }

    public function contact(){
        $this->load->view('Contact/Contact');
    }
    public function contactAdm(){
        $this->load->view('Contact/ContactAdm');
    }
    public function contactCust(){
        $data['cs'] = $this->Cs_model->ambil_data();
        $this->load->view('Contact/ContactCust', $data);
    }

    public function regis(){
        $this->load->view('Regis');
    }

    public function service(){
        $this->load->view('Cs/Cs_form');
    }

    public function beli(){
        $data['barang'] = $this->Barang_model->ambil_data();
        $username=$this->session->userdata('username');
        $this->load->view('Beli/Beli_form', $data);
    }

    public function infoCust(){
        $username=$this->session->userdata('username');
        $data = $this->Customer_model->ambil_data_user($username);
        $this->load->view('Customer/Customer_info', $data);
    }

    public function infoBeli(){
        $username=$this->session->userdata('username');
        $data = $this->Beli_model->ambil_data_user($username);
        $this->load->view('Beli/Beli_info', $data);
    }

}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */