<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Login extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //$this->load->model('login_model');
        $this->load->model('Admin_model');
        $this->load->model('Customer_model');
    }

    public function index()
    {	
		
		if(!$this->input->post()) //jika tidak ada input data post maka akan ke halaman login
		{
			$this->load->view('Login2');
		}
		else
		{

			$cek_login_adm = $this->Admin_model->cek_login_adm(
				$this->input->post('username'),
				$this->input->post('password')
				);
			$cek_login_cust = $this->Customer_model->cek_login_cust(
				$this->input->post('username'),
				$this->input->post('password')
				);
			if(!empty($cek_login_adm))
			{
				$this->session->set_userdata('username',$cek_login_adm->username);
				$this->session->set_userdata('logined',true);				
				redirect("Home/setting");
			}
			else if(!empty($cek_login_cust))
			{
				$this->session->set_userdata('username',$cek_login_cust->email);
				$this->session->set_userdata('logined',true);				
				redirect("Home/homeLoginCust");
			}
			else 
			{
				redirect("Home/login");
			}

		}
        
    } 
	
	public function logout()
    {
		$this->session->unset_userdata('logined');//hapus session userdata
		redirect("/");
    } 
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */